[build]
  publish = "build"
  command = "npm install && npm run build"
  functions = "netlify/functions"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 